name: Test build

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v14
        with:
          name: pineapplehunter
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: run check
        run: nix --quiet -L flake check

      - name: upload builds
        if: always()
        run: nix eval ".#checks.x86_64-linux" --json | jq ".[]" -r | cachix push pineapplehunter
